#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Auto-bump patch version on commit
echo "🔄 Auto-bumping version..."
yarn version patch

git add package.json .yarn/install-state.gz




echo "🎉 Pre-commit checks completed!"
